baseURL = '/'
languageCode = 'en-us'
title = 'The DXH Notes'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "posts"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "dxh"
hostname = "notes"
    [params.author]
    name = "dxh"  # Website and RSS feed author
    email = "dylan.x.h.developer@gmail.com"  # RSS feed email address

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/dylanxhernandez"

[[params.social]]
key = 1
name = "linkedin"
url = "https://linkedin.com/in/dxhernandez/"

[[params.social]]
key = 2
name = "email"
url = "mailto:dylan.x.h.developer@gmail.com"
