baseURL = '/'
languageCode = 'en-us'
title = 'The DXH Notes'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "dxh"
hostname = "gohugo.io"
    [params.author]
    name = "dxh"  # Website and RSS feed author
    email = "email@example.com"  # RSS feed email address

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/gohugoio"

[[params.social]]
key = 1
name = "linkedin"
url = "https://www.example.com"

[[params.social]]
key = 2
name = "email"
url = "mailto:email@example.com"
